### PR TITLE
Updated namespace

### LINKED ISSUE #144: Change namespace from org\bovigo\vfs to match package name
The current namespace was chosen at a time when there was no clear standard for PHP namespaces yet.  (And the author was under way too much Java influence.) As the package name is subject to a possible change (see #137) and a new major release has become feasible it is a good time to rethink the namespace and possibly switch to one which better matches the (future) package name. So while the `org\` prefix should definitely be dropped, the `vfs` part is subject to discussion. Possible options:

* `bovigo\vfs` - simply drop the `org\` prefix, and leave the remainder unchanged. Package name should be `bovigo\vfs` then. The change in source code using this library would be very simple then.
* `bogigo\vfsstream` - reflects the library name better, but requires even more changes by library users. However, if the use statements have to be changed anyway, this shouldn't be much of additional work.

Independent of which one is chosen the major version which introduces a change like this should still feature the old namespace but deprecating it, and only the major version thereafter should drop the old namespace altogether.

### PR DESCRIPTION
**Pull request by bizurkur**
This changes the primary namespace from `org\bovigo\vfs` to `bovigo\vfs`, but still maintains the `org\bovigo\vfs` namespace. Based this change on how Twig 2 did their [namespace migration](https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Cache/Null.php).

Closes #144

### CODE REVIEW

**Comment by allejo** [comment]
Thoughts on having our unit test namespace be `bovigo\vfs\Tests` instead of `bovigo\vfs`?

**Comment by bizurkur** [comment]
> Thoughts on having our unit test namespace be `bovigo\vfs\Tests` instead of `bovigo\vfs`?

I do think that's how it should be, just wasn't sure if I should do it as part of this or not. I'm up for either part of this or a separate PR.

**Comment by allejo** [comment]
Both the unit test files and namespace are being touched in this PR, so I don't see the harm in doing it in this one.

**Comment by mikey179** [comment]
> Thoughts on having our unit test namespace be bovigo\vfs\Tests instead of bovigo\vfs?

Not a fan of uppercase letters in namespace names, but if everyone agrees I'm fine with that.

**Comment by bizurkur** [comment]
Switched the test namespace to lowercase for consistency with everything else.

I generally write namespaces in StudlyCase (the same as a class name). Since they're all lowercase in the other files, it makes sense to keep it consistent.

**Pull request merged**
