### PR TITLE
.travis: enable 7.4snapshot

### PR DESCRIPTION
**Pull request by kornrunner**
Test against `7.4snapshot` on Travis

Ref: #189

### CODE REVIEW

**Comment by mikey179** [comment]
Definitely the right thing to do. Is there a specific reason you put 7.3 into the `allow_failures` section?

**Comment by kornrunner** [comment]
Yeah - I haven't checked if `7.3` is officially supported within `vfsStream`. Because it has a [failure](https://travis-ci.com/bovigo/vfsStream/jobs/218595306) - I didn't want this to be a showstopper if it gets merged in

**Comment by mikey179** [comment]
Oh, you are right. Also I was stupid - I had #172 opened just minutes before my comment. 🙈

**Comment by allejo** [comment]
I've merged #172 (which added 7.3 to Travis). Could you please rebase this on top of master?

As for allowed failures, I'd prefer only `nightly` but `7.4snapshot` can remain there for now while 7.4 compat changes are being made.

**Comment by kornrunner** [comment]
Of course, here it goes

**Comment by allejo** [comment]
Thank you @kornrunner!

**Pull request merged**
