### PR TITLE
Remove Composer lock file

### PR DESCRIPTION
**Pull request by allejo**
Do we actually *need* a lock file for a library? There's nothing for us to deploy so we don't need to lock in any of the dependencies. Our only dependencies are dev dependencies, which I don't think we need to lock.

### CODE REVIEW

**Comment by allejo** [comment]
> consistency between builds, the lockfile prevents unexpected upgrades of our dev dependencies.

I've got no argument against this, I agree that it'd let us replicate dev builds accurately if we need to track down some issue with our dev tools.

I think that not having a lock file, while slower, would let us actually find issues with our dev tools quicker. Since we'll always be using the latest version (per our `composer.json` requirements), we'd notice something amiss sooner rather than later when we update our dependencies. Removing the lock file would also allow us to remove the need for PRs like #194 and whichever new PR comes along that will update the phpstan dependency, which currently breaks with our 7.4snapshot testing. The lack of 7.4 compatability has already been fixed upstream (https://github.com/phpstan/phpstan/pull/2275) and will be available in `0.11.13` or whichever the next release is.

My thinking is that as long as our `composer.json` requirements are strict enough to prevent pulling down major breaking changes, we'd get the benefit of not having to worry about explicitly updating our dev dependencies and just triggering new builds instead.

**Comment by jaapio** [comment]
I have my doubts about this pr. But I would agree with a second opinion form another team member to have this merged. 

I requested a review from the team. Let's see what others are thinking about this :-)

**Comment by localheinz** [comment]
Personally, I would suggest to keep `composer.lock`

Also see http://naderman.de/slippy/slides/2018-01-26-composer-lock-demystified.pdf.

**Comment by jaapio** [comment]
We could start using dependabot. That will help use to keep up to date?

**Comment by allejo** [comment]
I'm not adamant about removing the lock file, I'm totally fine with keeping it for speed and reproducibility of builds, so I'll close this PR.

+1 from me for giving dependabot a try if others are interested as well.

**Pull request closed without merging**
