### PR TITLE
Added permission tests for "other" access

### LINKED ISSUE #167: Different behaviour for is_readable() between 1.6.5 and 2.0.0-dev
From #166, redacted:

```php
$root = vfsStream::setup('php-unit', 0777);
$root->chown(vfsStream::getCurrentUser());
$root->chgrp(vfsStream::getCurrentGroup());

$file = new vfsStreamFile('file.ext', 0400);
$file->chown(vfsStream::getCurrentUser() + 1);
$file->chgrp(vfsStream::getCurrentGroup() + 1);
$file->content('foobar');
$root->->addChild($file);

var_dump(is_readable($file->url()));
```
Using version **`1.6.5`** I get the following:
```
false
```
Using version **`2.0.x-dev`** I get the following:
```
true
```

As I don't have an explanation for this different behaviour right away this must be investigated.

### PR DESCRIPTION
**Pull request by bizurkur**
Issue https://github.com/bovigo/vfsStream/issues/167 noted a permission difference. The issue seems to have gone away and is working as expected. Adding tests to prevent regression.

Closes #167

### CODE REVIEW

**Comment by bizurkur** [comment]
OK, I noticed the build was failing only for Windows so I loaded up a Windows VM and got git and everything else installed in there and did some testing in the Windows environment.

I tested against this branch and the 1.6.5 release with just the basic test outlined in #167. In both cases, the `is_readable` check failed (it always saw the file as readable). Even using a real file it saw it as readable. Windows does not seem to honor the group/other permissions as expected. I could only get the `is_readable` check to fail by going to the file Properties, Security tab, and manually setting the Read permission to Deny.

On all *nix systems, everything seems to work as expected.

**Comment by allejo** [comment]
> In both cases, the `is_readable` check failed (it always saw the file as readable). Even using a real file it saw it as readable.

If this happens with a real file, does that mean this is a PHP bug on Windows or am I misunderstanding things? Or does PHP not handle file permissions on Windows the same way as *nix? I'm not familiar with the Windows filesystem so is it that different?

**Comment by mikey179** [comment]
> I tested against this branch and the 1.6.5 release with just the basic test outlined in #167. In both cases, the is_readable check failed (it always saw the file as readable). Even using a real file it saw it as readable. Windows does not seem to honor the group/other permissions as expected.

Have you tested if vfsStream is called at all? I have the suspicion that PHP on Windows might short circuit here and not even call the stream wrapper. If that's the case it should be added to the [list of known issues](https://github.com/bovigo/vfsStream/wiki/Known-Issues).

**Comment by bizurkur** [comment]
It does goes through the `vfsStream::url_stat()` as expected for the `is_readable()` call. The permissions ("mode") in the stat matched the same as my test on Mac. Everything looked correct to me... except it never honored the group/other permissions. If owner had read, php always returned is_readable as true even when the "owner" was different.

I'm more curious if this is because Windows [doesn't use the UID/GID](https://www.php.net/manual/en/function.stat.php#refsect1-function.stat-returnvalues) like *nix does. Windows always sets those values to `0`. The stream wrapper does correctly fake those values to `1` in the `chown`/`chgrp` calls in the test, but maybe something at php level ignores it when the OS is Windows?

I also thought it might be an issue with `clearstatcache()` needing to be called, but that didn't seem to be the case.

I'm honestly not sure if it's a possible bug or if it's just because Windows does permissions differently. My real file test I don't think was sufficient enough to call anything a bug, as I don't know of a good way to do a real `chown` on Windows. Most of my testing was through the stream wrapper. I can't rule out that it's a bug at the stream wrapper level, though.

We could definitely add it as a known issue if that's the way we want to go. I poked at this for hours last night and couldn't get anything to work.

The only good thing that came out of it is that I couldn't prove a difference between 1.6.5 (and 1.6.8) and 2.x, like the issue suggested was the case. On Windows, both branches failed on the same `is_readable` test and passed on everything else. Behavior seems to have stayed the same, so the issue can be closed.

**Comment by mikey179** [comment]
Thanks for trying to find out what's happening! I guess it needs someone who wants to dig into the PHP source itself to understand and find out what's going on. For the time being my suggestion would be to merge the PR as is, and to add it as a known issue.

**Comment by bizurkur** [comment]
Updated known issues list

**Pull request merged**
